### PR TITLE
remove the floating point action button

### PR DESCRIPTION
**Pull request by agarwalBinay18**
# Description 

i have removed the floating action button from the mainactiviy.java .
Fixes # 8

## Type of change
- Bug fix 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by pavitrawalia** [comment]
@agarwalBinay18  There are still some patches left which handle the floating-point actions. 
Also in Type of change, you have to mention bug fix instead of a new feature.
After you do the needful changes reply to this thread. I will then review the PR again

**Comment by agarwalBinay18** [comment]
i have removed the patches and fix the issue#8

**Comment by pavitrawalia** [comment]
@agarwalBinay18 please mention your full name in the pull request description

**Comment by agarwalBinay18** [comment]
binay agarwal

**Pull request merged**
